name: edf-adminconsole-local

services:
  adminconsole:
      tty: true
      pull_policy: always
      # image: edfialliance/admin-console-web:pre-alpha
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      restart: always
      container_name: edf-adminconsole-local
      environment:
        - EG_app__basePath=/edficonsole/v2.3/v7.2/ds4/saas/tx
      ports:
        - "8598:8598"