# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

# Node 20.x
FROM node@sha256:c628bdc7ebc7f95b1b23249a445eb415ce68ae9def8b68364b35ee15e3065b0f AS build
RUN apk --upgrade --no-cache add dos2unix=~7 bash=~5 gettext=~0 icu=~74 curl=~8 go=~1.23.9-r0

WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# Install all the dependencies
RUN npm ci

COPY . /app

RUN cp config.example.ports.json config.json

EXPOSE 8598

CMD ["npm", "run", "dev:docker"]