# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

FROM node:18-alpine AS build

WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# Install all the dependecies
RUN npm i

COPY ../. /app

RUN cp config.example.ports.json config.json

# Remove folders
RUN rm -r docker
RUN rm -r eng
RUN rm -r .github
RUN rm -r docs
RUN rm -r e2e

EXPOSE 8598

CMD ["npm", "run", "dev:docker"]