# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pull Request - Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  scan-actions-bidi:
    name: Scan Actions, scan all files for BIDI Trojan Attacks
    uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-config.json
  
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    permissions:
        security-events: write
    steps:

      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Dependency Review ("Dependabot on PR")
        if: ${{ github.event_name == 'pull_request' && !github.event.repository.fork }}
        uses: actions/dependency-review-action@9129d7d40b8c12c1ed0f60400d00c92d437adcce # v4.1.3

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169 # v3.28.0
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        if: success()
        uses: github/codeql-action/analyze@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169 # v3.28.0

  build:
    name: Build and typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Run the build
        run: npm run build

      - name: Run ESLint
        run: npm run lint

      # No unit tests to run yet, and linter is broken. SF 2/10/2025

  docker-analysis:
    name: Docker Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          [
            { name: "admin-console-local", path: "Dockerfile", type: "local" }
          ]
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
      name: Run Linter on ${{ matrix.dockerfile.name }} Dockerfile
      with:
        dockerfile: ${{ matrix.dockerfile.path }}
        failure-threshold: error

    - name: Build
      run: |
        docker build -f ${{ matrix.dockerfile.path }} -t ${{ matrix.dockerfile.name }} .
        
    - name: Analyze
      uses: docker/scout-action@67eb1afe777307506aaecb9acd9a0e0389cb99ae # v1.5.0
      with:
        command: cves
        image: local://${{ matrix.dockerfile.name }}
        sarif-file: sarif-${{ matrix.dockerfile.name }}.output.json
        summary: true

    - name: Upload SARIF result
      id: upload-sarif
      if: ${{ github.event_name != 'pull_request_target' }}
      uses: github/codeql-action/upload-sarif@48ab28a6f5dbc2a99bf1e0131198dd8f1df78169 #v3.28.0
      with:
        sarif_file: sarif-${{ matrix.dockerfile.name }}.output.json

