# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pre-Release
on:
  release:
    types:
      - prereleased
  workflow_dispatch:

permissions: read-all

env:
  ARTIFACTS_API_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  ARTIFACTS_USERNAME: ${{ secrets.AZURE_ARTIFACTS_USER_NAME }}
  GITHUB_TOKEN: ${{ secrets.PAT_ATTACH_TO_RELEASE }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  REF: ${{ github.ref_name }}
  IMAGE_NAME: ${{ vars.ED_FI_ADMIN_CONSOLE_IMAGE_NAME }}
  NPM_REGISTRY: ${{ vars.NPM_REGISTRY }} 
  MANIFEST_FILE: "./sbom/_manifest/spdx_2.2/manifest.spdx.json"

jobs:
  azure-publish:
    name: Publish to Azure Artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    outputs:
      hash-code: ${{ steps.hash-code.outputs.hash-code }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci
      
      - name: Transpile to JS
        run: npm run build

      - name: Create packages
        # Explicit step is not required for publishing, but it allows us to upload artifacts
        run: npm pack

      - name: Create .npmrc for Azure Artifacts publishing
        run: |
          echo "Configuring .npmrc for ${{ env.NPM_REGISTRY }}"
          set +x  # disable echo to shell so that the base64-encoded API key never escapes into the log.

          # Create the user .npmrc file with proper settings
          API_KEY=`echo -n "${{ env.ARTIFACTS_API_KEY }}" | base64`
          touch $HOME/.npmrc
          echo "; begin auth token" >> $HOME/.npmrc
          echo ${{ env.NPM_REGISTRY }}:username=${{ env.ARTIFACTS_USERNAME }} >> $HOME/.npmrc
          echo ${{ env.NPM_REGISTRY }}:_password=$API_KEY >> $HOME/.npmrc
          echo ${{ env.NPM_REGISTRY }}:email=techsupport@ed-fi.org >> $HOME/.npmrc
          echo "; end auth token" >> $HOME/.npmrc

      - name: Publish
        run: npm publish --tag dev

      - name: Generate hash codes for npm tarballs
        id: hash-code
        run: echo "hash-code=$(sha256sum *.tgz | base64 -w0)" >> $GITHUB_OUTPUT

      - name: Upload packages as artifacts
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: npm
          path: ./*.tgz
          if-no-files-found: error
          retention-days: 30

  docker-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          [
            { name: "development", path: "docker/Dockerfile", type: "local" },
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        name: Run Linter on ${{ matrix.dockerfile.name }} Dockerfile
        with:
          dockerfile: ${{ matrix.dockerfile.path }}
          failure-threshold: error

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Build
        run: |
          dockerfile=$(echo ${{matrix.dockerfile.path}} | awk -F"/" '{print $NF}')

          docker build -f $dockerfile -t ${{ matrix.dockerfile.name }} --build-arg="pre" .

      - name: Analyze
        uses: docker/scout-action@67eb1afe777307506aaecb9acd9a0e0389cb99ae # v1.5.0
        with:
          command: cves
          image: local://${{ matrix.dockerfile.name }}
          sarif-file: sarif-${{ matrix.dockerfile.name }}.output.json
          summary: true

      - name: Upload SARIF result
        id: upload-sarif
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/upload-sarif@cf7e9f23492505046de9a37830c3711dd0f25bb3 #codeql-bundle-v2.16.2
        with:
          sarif_file: sarif-${{ matrix.dockerfile.name }}.output.json
  
  docker-publish:
    name: Publish to Docker Hub
    permissions:
        actions: read
        contents: write
    runs-on: ubuntu-latest
    needs:
      - azure-publish
      - docker-analysis
    steps:
      - name: Wait 20s
        # Give Azure Artifacts caching a moment to catch up
        run: sleep 20

      - name: Prepare Tags
        id: prepare-tags
        run: |
          BASE="${{ env.IMAGE_NAME }}"

          REF="${{ env.REF }}"
          NPM_VERSION=${REF:1}  # strip off the leading 'v'

          if [[ $REF =~ "pre" ]]
          then
            # Pre-releases get the version and the tag "pre"
            TAGS="${{ env.IMAGE_NAME }}:${REF},${{ env.IMAGE_NAME }}:pre"
          else
            # Releases get the version, plus shortened form for minor release.
            # We are not using shortened form for major or using "latest"
            # because they are too imprecise.
            MINOR=`echo ${REF} | awk -F"." '{print $1"."$2}'`
            TAGS="${{ env.IMAGE_NAME }}:${REF},${{ env.IMAGE_NAME }}:${MINOR}"
          fi

          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
          echo "NPM_VERSION=$NPM_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226  # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d  # v3.0.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934  # v5.0.0
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09  # v5.0.0
        with:
          context: "{{defaultContext}}:/"
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:pre
          cache-to: type=inline
          build-args: ML_VERSION=${{ steps.prepare-tags.outputs.NPM_VERSION }}
          file: docker/Dockerfile
          tags: ${{ steps.prepare-tags.outputs.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  sbom-create:
    name: Create SBOM for NPM Packages
    runs-on: ubuntu-latest
    needs: azure-publish
    permissions:
      actions: read
      contents: write
    outputs:
      sbom-hash-code: ${{ steps.sbom-hash-code.outputs.sbom-hash-code }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Artifacts
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 #v4.1.1
        with:
          name: npm

      - name: Generate Software Bill of Materials (SBOM) - API
        shell: pwsh
        run: |
          $url = "https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64"
          $out = "$($env:RUNNER_TEMP)/sbom-tool"
          Invoke-RestMethod -Uri $url -OutFile $out
          chmod +x $out
          dotnet tool install --global Microsoft.Sbom.DotNetTool
          New-Item -Path sbom -Type Directory
          &$out generate `
              -b . `
              -pn "Ed-Fi-Admin-Console" `
              -pv ${{ env.REF }} `
              -nsb https://ed-fi.org `
              -m sbom `
              -ps "Ed-Fi Alliance"

      - name: Upload SBOM
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: admin-console-SBOM
          path: ${{ env.MANIFEST_FILE }}
          if-no-files-found: error
          retention-days: 30

      - name: Store hash code for SBOM
        id: sbom-hash-code
        shell: bash
        run: |
          # sha256sum returns "<hashcode>  <name of file". Split that and return only the <hashcode>.
          sbom_hash=$(sha256sum ./${{ env.MANIFEST_FILE }} | awk '{split($0,a); print a[1]}')
          echo "sbom-hash-code=$sbom_hash" >> $GITHUB_OUTPUT

  sbom-attach:
    name: Attach SBOM file
    runs-on: ubuntu-latest
    needs:
      - sbom-create
      - azure-publish
    permissions:
      actions: read
      contents: write
    steps:
      - name: Download the SBOM
        uses: Ed-Fi-Alliance-OSS/slsa-github-generator/.github/actions/secure-download-artifact@main
        with:
          name: admin-console-SBOM
          path: ${{ env.MANIFEST_FILE }}
          sha256: "${{ needs.sbom-create.outputs.sbom-hash-code }}"

      - name: Attach to release
        shell: pwsh
        run: |
          $release = "${{ env.REF }}"
          $repo = "${{ github.repository }}"
          $token = "${{ secrets.GITHUB_TOKEN }}"
          $file = "${{ env.MANIFEST_FILE }}"
          $uploadName = "admin-console-SBOM.zip"
          $url = "https://api.github.com/repos/$repo/releases/tags/$release"
          $gh_headers = @{
              "Accept"        = "application/vnd.github+json"
              "Authorization" = "Bearer $token"
          }
          $response = Invoke-RestMethod -Uri $url -Headers $gh_headers
          $releaseId = $response.id
          $url = "https://uploads.github.com/repos/$repo/releases/$releaseId/assets"
          Compress-Archive $file -DestinationPath $uploadName
          $gh_headers["Content-Type"] = "application/octet"
          Invoke-RestMethod -Method POST `
              -Uri "$($url)?name=$($uploadName)" `
              -Headers $gh_headers `
              -InFile $uploadName

  provenance-create:
    name: Create Provenance
    needs: azure-publish
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: Ed-Fi-Alliance-OSS/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects: ${{ needs.azure-publish.outputs.hash-code }}
      provenance-name: admin_console.intoto.jsonl
      upload-assets: true
      # TODO: remove this after this issue is resolved: https://github.com/slsa-framework/slsa-github-generator/issues/876
      compile-generator: true