// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

import { AppUserRole } from '../../../core/AppUser.types'

export interface GetUsersListRequest {
    pageIndex: number  
    pageSize: number
    orderBy: string 
    filter?: string
}

export interface GetUserProfileByIdRequest {
    userId: string 
}

export interface ActivateUserRequest {
    userId: string 
    tenantId: string
}

export interface DeactivateUserRequest {
    userId: string 
    tenantId: string
} 

export interface GetOrganizationsRequest {
    pageIndex: number  
    pageSize: number
    orderBy?: string 
    filter?: string
}

export interface GetStaffClassificationsRequest {
    pageIndex: number  
    pageSize: number
    orderBy?: string 
    filter?: string
}

export interface GetUserEducationOrganizationsRequest {
    userId: string
}

export interface CreateUserEducationOrganizationsRequest {
    userId: string
    tenantId: string
    educationOrganizationId: string
    educationOrganizationName: string
    staffClassifications: string[]
}

export interface UpdateUserEducationOrganizationsRequest {
    userId: string
    tenantId: string
    educationOrganizationId: string
    staffClassifications: string[]
}

export interface DeleteUserEducationOrganizationsRequest {
    userId: string
    educationOrganizationId: string
}

export interface AssignLicenseRequest {
    applicationId: string 
    subscriptionId: string 
    tenantId: string 
    userId?: string
    roles?: string[]
}

export interface RevokeLicenseRequest {
    applicationId: string 
    subscriptionId: string 
    tenantId: string 
    userId: string
}

export interface AddUserRequest {
    tenantId: string 
    userName: string 
    firstName: string 
    lastName: string 
    email: string 
    role: AppUserRole
    lockOutEnabled: boolean
    password?: string
    autoGeneratedPassword: boolean 
    twoFactorEnabled: boolean
    assignLicenseRequests: AssignLicenseRequest[]
}

export interface UpdateUserRequest {
    tenantId: string 
    userId: string
    firstName: string 
    lastName: string 
    email: string
    role: string 
}

export interface CheckUserEmailRequest {
    email: string
}

export interface Inviter {
    firstName: string 
    lastName: string
}

export interface InviteUserRequest {
    tenantId: string 
    firstName: string 
    lastName: string 
    email: string 
    inviter: Inviter
    role: AppUserRole
    assignLicenseRequests: AssignLicenseRequest[]
    invitingUserDisplayName: string
    dontSendEmail?: boolean
}

export interface DeleteUserRequest {
    userId: string
}

export interface DeleteInvitationRequest {
    invitationId: string
}

export interface GetInvitationsListRequest {
    pageIndex: number  
    pageSize: number
    orderBy: string 
    filter?: string
}

export interface AssignBulkLicensesRequest {
    tenantId: string 
    userId: string 
    assignLicenseRequests: AssignLicenseRequest[]
}

export interface RevokeBulkLicensesRequest {
    tenantId: string 
    userId: string 
    revokeLicenseRequests: RevokeLicenseRequest[]
}